package me.tbsten.compose.dom.generate

import com.squareup.kotlinpoet.ClassName

val NotEditMessage = """
/* 
 *
 * THIS FILE IS AUTO GENERATED .
 * DO NOT EDIT THIS FILE .
 *
 */
""".trimIndent()


const val LibraryPackageName = "me.tbsten.compose.dom"
const val ElementsPackageName = "$LibraryPackageName.elements"
const val AttributesPackageName = "$LibraryPackageName.attributes"

fun libraryClassName(simpleName: String) = ClassName(LibraryPackageName, simpleName)
